name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
          deno-version: v1.x
      - run: deno test -A
